### ISSUE TITLE
React in the content script

### ISSUE THREAD

**Issue by onikienko** [extend-chrome/js-react-boilerplate#1]
I'm trying to import React in the `src/content/index.js`:
``` javaScript
// src/content/index.j
import React from 'react'
console.log('content script')
```
But during the build I see this error:
> [!] (plugin chrome-extension) Error: Could not load chunks\react.development-737c30e9.js (imported by content\index.js): Could not load: chunks\react.development-737c30e9.js

The boilerplate is clean. I just started by adding React to the content script.
React works in the popup.
Btw, I do not see `dist/chunks` folder. Is it possible that I missed something?

**Comment by jacksteamdev** [comment]
@onikienko Thanks for letting us know about this! We've confirmed this bug, it looks like something is wrong with the way `output.chunkFileNames` is processed. If you look, `react.development-737c30e9.js` is probably in `dist`.

I've set aside some time to work on it tomorrow.

**Comment by rxliuli** [comment]
Is it fixed? Currently chrome still warns:

```js
Denying load of chrome-extension:///chunks/react-dom.development-a6c98dc2.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
```

**Comment by AmySteam** [comment]
Hey everyone, this bug should be fixed now 🎉.

Please upgrade to the latest version `npm i rollup-plugin-chrome-extension@latest`

Amy

**Comment by rxliuli** [comment]
> Hey everyone, this bug should be fixed now 🎉.
> 
> Please upgrade to the latest version `npm i rollup-plugin-chrome-extension@latest`
> 
> Amy

The error still occurs:

![image](https://user-images.githubusercontent.com/24560368/110559707-adb3bf00-817f-11eb-9ee7-f85c4968d1a8.png)
![image](https://user-images.githubusercontent.com/24560368/110559725-b3a9a000-817f-11eb-81e6-1961dc1f070b.png)

ref: https://github.com/rxliuli/joplin-search-intergration/blob/fd6ba833aa7b1b37cca53a8bf7ebd0d732a959eb/src/content/renderNoteResult.tsx#L25

**Comment by jacksteamdev** [comment]
@rxliuli :wave: Thanks for reaching out!

I cloned https://github.com/rxliuli/joplin-search-intergration and was able to get it to build successfully with some small changes. I've added these changes to this boilerplate, hopefully this takes care of it.

BTW, I never saw the `Maximum call stack size exceeded` error, but it's almost certainly not a bundling problem: https://stackoverflow.com/a/6095695/4842857

**Comment by rxliuli** [comment]
> @rxliuli 👋 Thanks for reaching out!
> 
> I cloned https://github.com/rxliuli/joplin-search-intergration and was able to get it to build successfully with some small changes. I've added these changes to this boilerplate, hopefully this takes care of it.
> 
> BTW, I never saw the `Maximum call stack size exceeded` error, but it's almost certainly not a bundling problem: https://stackoverflow.com/a/6095695/4842857

You are right. The reason for this error is actually due to proxying console access. In addition, I have merged your two submissions and finally successfully used react in content-scripts, thank you very much!
https://github.com/rxliuli/joplin-search-intergration/pull/2
